//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmers_App.Models
{
    using Microsoft.Ajax.Utilities;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.ModelBinding;

    public partial class FARMER
    {
        public int UserID { get; set; }

        [Required(ErrorMessage = "This field is required *")]
        [StringLength(50, ErrorMessage = "Name cannot be 50 characters long")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z'\s-]*$", ErrorMessage = "Please start with a capital letter")]
        [DisplayName("FIRST NAME")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "This field is required *")]
        [StringLength(50, ErrorMessage = "Name cannot be 50 characters long")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z'\s-]*$", ErrorMessage = "Please start with a capital letter")]
        [DisplayName("LAST NAME")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "This field is required *")]
        [StringLength(50, ErrorMessage = "Name cannot be 50 characters long")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z'\s-]*$", ErrorMessage = "Please start with a capital letter")]
        [DisplayName("VILLAGE NAME")]
        public string Village_Name { get; set; }

        [Required(ErrorMessage = "This field is required *")]
        [DisplayName("TYPE OF FARMING")]
        public string TYPE_OF_FARMING { get; set; }

        [Required(ErrorMessage = "This field is required *")]
        [DisplayName("PROVINCE")]
        public string PROVINCE { get; set; }

        [Required(ErrorMessage = "This field is required *")]
        [DisplayName("GENDER")]
        public string GENDER { get; set; }
    
        public virtual FARM_TYPES FARM_TYPES { get; set; }
        public virtual GENDER GENDER1 { get; set; }
        public virtual PROVINCE PROVINCE1 { get; set; }
    }
}
